version: '3.8'

services:
  web:
    build: ./g4_10
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=demo_user
      - POSTGRES_PASSWORD=demo_password
      - POSTGRES_DB=demo_db

volumes:
  postgres_data: