version: '3.8'

services:
  web:
    build: ./g4_10
    command: gunicorn g4_10.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/g4_10/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=demo_user
      - POSTGRES_PASSWORD=demo_password
      - POSTGRES_DB=demo_db
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/g4_10/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: